Re-implementation of adaptive mutation strength
WilmerLab/HTSOHM-dev pull request #32
Opened 2017-03-29 16:17 UTC by akaija

This PR separates the querying of mutation strengths at time of mutation from a generation-wide step in which all mutation strengths are calculated for parents in the current generation, before continuing to the next generation. It also includes a fix for when workers get stuck in a retesting loop.

2017-03-29 18:20 UTC, paulboone requested changes

2017-03-29 18:20 UTC, paulboone commented on htsohm/htsohm.py
> +
should be in a different commit?

2017-03-29 18:20 UTC, paulboone commented on htsohm/htsohm.py
> +                mutation_strength = get_mutation_strength(run_id, gen-1, parent_material)
SQUASH

2017-03-29 18:20 UTC, paulboone commented on htsohm/htsohm.py
> +            (
no text defined?

2017-03-29 18:20 UTC, paulboone commented on htsohm/htsohm.py
> +
Consider just using ORM?

2017-03-29 18:20 UTC, paulboone commented on htsohm/htsohm.py
> +
While we are not deleting rows, we need another where condition so that we only get rows < materials per generation so we don't include the excess rows in our calculation.

2017-03-29 18:20 UTC, paulboone commented on htsohm/htsohm.py
> +from sqlalchemy.sql import text
wrong commit

2017-03-29 18:20 UTC, paulboone commented on htsohm/htsohm.py
> +                'select parent_id from materials where run_id=\'{0}\' and '
This was never working, so should have been squashed.

2017-03-29 18:20 UTC, paulboone commented on htsohm/htsohm.py
> +                            )
unnecessary three lines

2017-03-29 18:20 UTC, paulboone commented on htsohm/htsohm.py
> +                ):
This is NOT a  print change. This is an important functional change that should be broken into a separate commit

2017-03-29 18:20 UTC, paulboone commented on htsohm/htsohm.py
> +                'select parent_id from materials where run_id=\'{0}\' and '
Also, this is NOT a  print change. This is a change that should be broken into a separate commit.

2017-03-29 18:20 UTC, paulboone commented on htsohm/htsohm.py
> +
Just use MutationStrength.get_prior(); then you don't need this method

2017-03-29 18:20 UTC, paulboone commented on htsohm/htsohm.py
> +                        parent_material, parent_pseudo_material, mutation_strength.strength, gen)
if the parameter has changed for mutate_pseudo_material(), then that should be in this commit as well.

or is this correct?

2017-03-29 18:20 UTC, paulboone commented on htsohm/htsohm.py
> +                        parent_material, parent_pseudo_material, mutation_strength.strength, gen)
Probably doesn't work in all cases because sometimes the mutate_pseudo_material() returns a mutation_strength object and sometimes the strength itself. But if you replace with get_prior(), it should be ok.

2017-03-29 18:20 UTC, paulboone commented on htsohm/htsohm.py
>                         )
Do something like:         
def print_block(msg):
print("="*80 + '%s' % msg + "="*80)  

so that all your prints here can be one line

2017-03-29 18:20 UTC, paulboone commented on htsohm/htsohm.py
> +def calculate_mutation_strength(run_id, generation, parent):
This would be much clearer and make more sense if it was a function of the bin, not the parent. This was causing you, me, Chris all confusion. So if you refactor this, and the upstream calls, will make all this make more sense.

2017-03-29 18:20 UTC, paulboone commented on htsohm/htsohm.py
> +                    if parent_material.bin not in ms_bins:
b/c of change to calculate_mutation_strength, you'll want to iterate over bins, not parent_ids

2017-03-29 18:20 UTC, paulboone commented on htsohm/htsohm.py
> +            print('WARNING: ZeroDivisionError - material.calculate_retest_result(tolerance)')
I think this should work, and I'm A-OK with it.

Still make sure though that we're not throwing that ZeroDivisionError. And we still want to find the source of the problem!

2017-03-29 18:20 UTC, paulboone commented on htsohm/htsohm.py
> +                    parent_pseudo_material = load_pseudo_material(run_id, parent_material)
If you move this line above the while, you shoudn't need the check below.

2017-03-29 18:20 UTC, paulboone commented on htsohm/htsohm.py
> +                if not 'parent_pseudo_material' in locals():
should never need to use locals(); it's a code smell

2017-03-30 14:53 UTC, akaija commented on htsohm/htsohm.py
> +from sqlalchemy.sql import text
done.

2017-03-30 14:53 UTC, akaija commented on htsohm/htsohm.py
> +                'select parent_id from materials where run_id=\'{0}\' and '
done.

2017-03-30 14:58 UTC, akaija commented on htsohm/htsohm.py
> +                ):
Done.

2017-03-30 15:19 UTC, akaija commented on htsohm/htsohm.py
> +                            )
Done.

2017-03-30 15:45 UTC, akaija commented on htsohm/htsohm.py
> +def calculate_mutation_strength(run_id, generation, parent):
we should discuss this, calculating the mutation strength calls calculate_percent_children_in_bin which is a class method of the material itself, furthermore this method requires the parent bin AND parent id to find children, so we need to query the parent_id anyway. i would have to pull calculate_percent_children_in_bin into htsohm/htsohm.py or move it somewhere else...

2017-03-30 15:52 UTC, akaija commented on htsohm/htsohm.py
>                         )
Done.

2017-04-12 17:27 UTC, paulboone commented on htsohm/htsohm.py
> +def calculate_mutation_strength(run_id, generation, parent):
Move calculate_percent_children_in_bin off of material and just make it a function of bin in htsohm. Then calculate_mutation_strength won't need the parent either and can just be a function of bin.

2017-04-12 17:46 UTC, paulboone requested changes

2017-04-12 17:46 UTC, paulboone commented on htsohm/simulation/gas_adsorption_1.py
>              "SimulationType                 MonteCarlo\n" +
This commit looks unnecessary now.

2017-04-12 17:46 UTC, paulboone commented on htsohm/htsohm.py
> +
Session.query(Table.id).distinct()... did this in later commit? should have squashed it here.

2017-04-12 17:46 UTC, paulboone commented on htsohm/htsohm.py
> +
If you were going to placeholder this, you have to use pass; but this doesn't need to be placeholdered. These last three lines should be squashed with next commit.

2017-04-13 14:48 UTC, akaija commented
this should be good to go?

2017-04-26 17:20 UTC, paulboone requested changes
Looks pretty good except for:
- the var name bin
- comments

2017-04-26 17:20 UTC, paulboone commented on htsohm/htsohm.py
> +    mutation_strength_key = [run_id, generation] + bin
bin is a bad variable name because it is also the name of a built-in method

2017-04-26 17:20 UTC, paulboone commented on htsohm/htsohm.py
> +    """
comment here is wrong. This method REALLY needs a comment so we can understand what it is doing. I think we are: finding ALL materials in the provided generation whose PARENT is in the provided bin. Which I think makes sense. The code looks good. But needs a description and parameter docs.

2017-04-26 17:20 UTC, paulboone commented on htsohm/htsohm.py
Update comment.

2017-04-26 17:20 UTC, paulboone commented on htsohm/htsohm.py
> +                            )
I see the "Done" but I also still see all the extra lines...?

2017-05-02 23:28 UTC, paulboone requested changes

2017-05-02 23:28 UTC, paulboone commented on htsohm/htsohm.py
> +    ```
Definitely do not need to dupe the query here. It's already in the code!

2017-05-02 23:28 UTC, paulboone commented on htsohm/htsohm.py
> +    """Find the fraction of children generated by all parents from a particular
still have variable named bin, which duplicates python built-in.

2017-05-18 18:23 UTC, paulboone approved these changes

2017-05-18 18:23 UTC, merged